# 数据操作

## 导入pytorch工具，注意敲的是torch

In [2]:
import torch

## 张量(Tensor)

张量可以看作是一个多维数组。标量可以看作是0维张量，向量可以看作1维张量，矩阵可以看作是二维张量。Tensor和NumPy的多维数组非常类似.
https://zhuanlan.zhihu.com/p/140260245  

In [4]:
x=torch.arange(12)#生成一维张量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 访问张量形状

In [6]:
x.shape

torch.Size([12])

### 访问张量中元素个数

In [9]:
#注意括号
x.numel()

12

### 改变张量形状，不变元素数量和数值

In [10]:
x=x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 设置数值为全0，1或其它常量或从特定分布中随机采样的数字

In [11]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### 通过提供<u>包含数值</u>的python列表（或嵌套列表）赋值

In [14]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])#从数据中构造一个张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 标准算术运算

In [15]:
x=torch.tensor([1.0,2,4,8])#1.0是浮点元素
y=torch.tensor([2,2,2,2])#全为整数
x+y,x-y,x*y,x/y,x**y#**表示幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

标准运算符均可升级为按元素运算,按元素运算要求被运算的两个矩阵或数组结构相同

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### 将多个张量连结在一起

In [5]:
x=torch.arange(24,dtype=torch.float32).reshape((2,3,4))#dtype指定张量数据类型,注意从右到左维度越来越高
y=torch.arange(24,dtype=torch.int).reshape((2,3,4))
print(x)
print(y)
#y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])#怎么用tensor构建多维张量？
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1),torch.cat((x,y),dim=2)#dim=0,按行合并，即合并单元是行；dim=1是按列合并.dim的数值x对应shape中第x维。

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)


(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]],
 
         [[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15., 12., 13., 14., 15.],
   

### 按逻辑运算构建张量

In [30]:
#此时元素为布尔值
x==y

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])

### 对张量中所有元素求和会得到只有一个元素的张量

In [32]:
x.sum()

tensor(276.)

### 广播机制（broadcasting mechanism）

它允许在执行数组运算时自动扩展数组的形状，使得不同形状的数组可以进行数学运算。

广播机制允许在不复制数据的情况下，将较小的数组“广播”到较大数组的大小，以便它们具有兼容的形状。要使两个张量或数组可广播，必须满足以下条件

* 每个张量至少有一个维度。

* 从尾部维度开始遍历时，两个张量的每个维度必须相等，或其中一个维度为1，或其中一个维度不存在。

如果两个张量是“可广播的”，则广播过程遵循以下步骤：

* 如果两个张量的维度数不同，较小维度的张量会在前面增加维度，直到两者维度数相等。

* 对于每个维度，如果一个张量的维度为1，则该维度会被扩展以匹配另一个张量的相应维度。扩展方式是复制

**弊端：会忽略张量维度问题的报错**

In [34]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [35]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 元素访问

In [40]:
#最后一个元素
x[-1],x[1:3]
#第2和3个元素


(tensor([[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]),
 tensor([[[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]))

### 元素写入

In [42]:
#使用索引给特定元素赋值
x[1,1,2]=9
x

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17.,  9., 19.],
         [20., 21., 22., 23.]]])

In [43]:
#为多个元素赋相同值
x[0,0:2,:]=12
x

tensor([[[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17.,  9., 19.],
         [20., 21., 22., 23.]]])

### 原地操作避免新结果分配内存(针对大的张量）

In [44]:
#反例
before=id(y)
y=y+x
id(y)==before

False

In [45]:
#原地操作
z=torch.zeros_like(y)#z的shape以及dtype与y相同，但value=0
print('id(z):',id(z))
z[:]=x+y#本质是对z赋值
print('id(z):',id(z))
#另，当后续不会再使用旧的x时，也可以对x赋值来减少内存开销
before=id(x)
x+=y#or x[:]=x+y
id(x)==before

id(z): 2085924231272
id(z): 2085924231272


True

### 转换为numpy张量以及回转

In [47]:
A=x.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
#将size=1的张量转换为标量
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理

In [8]:
#创建人工数据集
import os#导入 os 模块，以便在代码中使用与操作系统交互的功能

os.makedirs(os.path.join('..','data'),exist_ok=True)#创建一个名为 data 的文件夹。这个文件夹的路径是相对路径 ..（表示上一级目录）和 data 组合而成。参数 exist_ok=True 表示如果目录已经存在，不会引发错误
data_file=os.path.join('..','data','house_tiny.csv')#创建一个变量 data_file，其值是组合了上一级目录和 data 文件夹下的文件名 house_tiny.csv 的完整路径
with open(data_file,'w') as f:#使用 with 语句可以确保在代码块结束后自动关闭文件。
    f.write('NumRooms,Alley,Price\n')#colname
    f.write('NA,Pave,127500\n')#each line one sample
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 加载数据集

In [6]:
#pip install pandas


   ---------------------------------------- 8.7/8.7 MB 60.7 kB/s eta 0:00:00
   --------------------------------------- 508.0/508.0 kB 57.6 kB/s eta 0:00:00


In [9]:
import pandas as pd

data=pd.read_csv(data_file)
print(data)#直接data更好看

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### 处理缺失值

In [10]:
#插值
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]#取data的前两列，这些列通常代表输入特征；最后一列作为输出特征
inputs=inputs.fillna(inputs.mean())#设置na为非空值的均值，注意string类型下无效
print(inputs)
#对于inputs中的类别值或离散值，将NA视为一个类别
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)
#inputs和outputs中所有条目均为数值类型，转化为张量
import torch
x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

**离散值：**数值类型，通常为int。分为间隔（如温度）和比率（如速度）

**类别值：**字符串类型，分为有序和无序